.TH "com.thealgorithms.strings.CheckAnagrams" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.strings.CheckAnagrams
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static boolean \fBisAnagrams\fP (String s1, String s2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Two strings are anagrams if they are made of the same letters arranged differently (ignoring the case)\&. 
.SH "Member Function Documentation"
.PP 
.SS "static boolean com\&.thealgorithms\&.strings\&.CheckAnagrams\&.isAnagrams (String s1, String s2)\fC [static]\fP"
Check if two strings are anagrams or not
.PP
\fBParameters\fP
.RS 4
\fIs1\fP the first string 
.br
\fIs2\fP the second string 
.RE
.PP
\fBReturns\fP
.RS 4
.PP
.nf
true 
.fi
.PP
 if two string are anagrams, otherwise 
.PP
.nf
false 

.fi
.PP
 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
