.TH "com.thealgorithms.conversions.IntegerToRoman" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.conversions.IntegerToRoman
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static String \fBintegerToRoman\fP (int num)"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Converting Integers into Roman Numerals
.PP
('I', 1); ('IV',4); ('V', 5); ('IX',9); ('X', 10); ('XL',40); ('L', 50); ('XC',90); ('C', 100); ('D', 500); ('M', 1000); 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
