.TH "com.thealgorithms.datastructures.lists.MergeSortedSinglyLinkedList" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.lists.MergeSortedSinglyLinkedList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.thealgorithms\&.datastructures\&.lists\&.SinglyLinkedList\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static \fBSinglyLinkedList\fP \fBmerge\fP (\fBSinglyLinkedList\fP listA, \fBSinglyLinkedList\fP listB)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.datastructures\&.lists\&.MergeSortedSinglyLinkedList\&.main (String[] arg)\fC [static]\fP"
Driver Code 
.PP
Reimplemented from \fBcom\&.thealgorithms\&.datastructures\&.lists\&.SinglyLinkedList\fP\&.
.SS "static \fBSinglyLinkedList\fP com\&.thealgorithms\&.datastructures\&.lists\&.MergeSortedSinglyLinkedList\&.merge (\fBSinglyLinkedList\fP listA, \fBSinglyLinkedList\fP listB)\fC [static]\fP"
Merge two sorted SingleLinkedList
.PP
\fBParameters\fP
.RS 4
\fIlistA\fP the first sorted list 
.br
\fIlistB\fP the second sored list 
.RE
.PP
\fBReturns\fP
.RS 4
merged sorted list 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
