.TH "com.thealgorithms.datastructures.graphs.A_Star" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.graphs.A_Star
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static PathAndDistance \fBaStar\fP (int from, int to, Graph graph, int[] heuristic)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
