.TH "com.thealgorithms.maths.PalindromeNumber" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.PalindromeNumber
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static boolean \fBisPalindrome\fP (int number)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static boolean com\&.thealgorithms\&.maths\&.PalindromeNumber\&.isPalindrome (int number)\fC [static]\fP"
Check if 
.PP
.nf
n 

.fi
.PP
 is palindrome number or not
.PP
\fBParameters\fP
.RS 4
\fInumber\fP the number 
.RE
.PP
\fBReturns\fP
.RS 4
.PP
.nf
true 
.fi
.PP
 if 
.PP
.nf
n 

.fi
.PP
 is palindrome number, otherwise 
.PP
.nf
false 

.fi
.PP
 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
