.TH "com.thealgorithms.devutils.searches.SearchAlgorithm" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.devutils.searches.SearchAlgorithm
.SH SYNOPSIS
.br
.PP
.PP
Inherited by com\&.thealgorithms\&.searches\&.BinarySearch, com\&.thealgorithms\&.searches\&.ExponentialSearch, \fBcom\&.thealgorithms\&.searches\&.FibonacciSearch\fP, \fBcom\&.thealgorithms\&.searches\&.IterativeBinarySearch\fP, \fBcom\&.thealgorithms\&.searches\&.IterativeTernarySearch\fP, \fBcom\&.thealgorithms\&.searches\&.JumpSearch\fP, \fBcom\&.thealgorithms\&.searches\&.LinearSearch\fP, com\&.thealgorithms\&.searches\&.LowerBound, \fBcom\&.thealgorithms\&.searches\&.TernarySearch\fP, and com\&.thealgorithms\&.searches\&.UpperBound\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "< T extends Comparable< T > int \fBfind\fP (T array[], T key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The common interface of most searching algorithms
.PP
\fBAuthor\fP
.RS 4
Podshivalov Nikita (https://github.com/nikitap492) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "< T extends Comparable< T > int com\&.thealgorithms\&.devutils\&.searches\&.SearchAlgorithm\&.find (T array[], T key)"

.PP
\fBParameters\fP
.RS 4
\fIkey\fP is an element which should be found 
.br
\fIarray\fP is an array where the element should be found 
.br
\fI<T>\fP Comparable type 
.RE
.PP
\fBReturns\fP
.RS 4
first found index of the element 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
