.TH "com.thealgorithms.searches.IterativeBinarySearch" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.searches.IterativeBinarySearch
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.thealgorithms\&.devutils\&.searches\&.SearchAlgorithm\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Binary search is one of the most popular algorithms This class represents iterative version \fBBinarySearch\fP Iterative binary search is likely to have lower constant factors because it doesn't involve the overhead of manipulating the call stack\&. But in java the recursive version can be optimized by the compiler to this version\&.
.PP
Worst-case performance O(log n) Best-case performance O(1) Average performance O(log n) Worst-case space complexity O(1)
.PP
\fBAuthor\fP
.RS 4
Gabriele La Greca : https://github.com/thegabriele97 
.PP
Podshivalov Nikita (https://github.com/nikitap492) 
.RE
.PP
\fBSee also\fP
.RS 4
SearchAlgorithm 
.PP
BinarySearch 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
