.TH "com.thealgorithms.strings.CharactersSame" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.strings.CharactersSame
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static boolean \fBisAllCharactersSame\fP (String s)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static boolean com\&.thealgorithms\&.strings\&.CharactersSame\&.isAllCharactersSame (String s)\fC [static]\fP"
check if all the characters of a string are same
.PP
\fBParameters\fP
.RS 4
\fIs\fP the string to check 
.RE
.PP
\fBReturns\fP
.RS 4
.PP
.nf
true 
.fi
.PP
 if all characters of a string are same, otherwise 
.PP
.nf
false 

.fi
.PP
 
.RE
.PP

.SS "static void com\&.thealgorithms\&.strings\&.CharactersSame\&.main (String[] args)\fC [static]\fP"
Driver Code 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
