.TH "com.thealgorithms.maths.TrinomialTriangle" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.TrinomialTriangle
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBTrinomialValue\fP (int n, int k)"
.br
.ti -1c
.RI "static void \fBprintTrinomial\fP (int n)"
.br
.ti -1c
.RI "static void \fBmain\fP (String argc[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
The trinomial triangle is a variation of Pascal’s triangle\&. The difference between the two is that an entry in the trinomial triangle is the sum of the three (rather than the two in Pasacal’s triangle) entries above it
.PP
Example Input: n = 4 Output 1 1 1 1 1 2 3 2 1 1 3 6 7 6 3 1 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
