.TH "com.thealgorithms.datastructures.buffers.CircularBuffer" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.buffers.CircularBuffer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCircularBuffer\fP (int buffer_size)"
.br
.ti -1c
.RI "Character \fBreadOutChar\fP ()"
.br
.ti -1c
.RI "boolean \fBwriteToCharBuffer\fP (char c)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)  throws InterruptedException "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "final int \fB_buffer_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
