.TH "com.thealgorithms.sorts.StoogeSort" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.sorts.StoogeSort
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.thealgorithms\&.sorts\&.SortAlgorithm\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Amir Hassan (https://github.com/ahsNT) 
.RE
.PP
\fBSee also\fP
.RS 4
\fBSortAlgorithm\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
