.TH "com.thealgorithms.maths.BinaryPow" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.BinaryPow
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBbinPow\fP (int a, int p)"
.br
.ti -1c
.RI "static void \fBtest\fP (int a, int p)"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.maths\&.BinaryPow\&.binPow (int a, int p)\fC [static]\fP"
Calculate a^p using binary exponentiation \fCBinary-Exponentiation\fP
.PP
\fBParameters\fP
.RS 4
\fIa\fP the base for exponentiation 
.br
\fIp\fP the exponent - must be greater than 0 
.RE
.PP
\fBReturns\fP
.RS 4
a^p 
.RE
.PP

.SS "static void com\&.thealgorithms\&.maths\&.BinaryPow\&.main (String[] args)\fC [static]\fP"
Main Function to call tests
.PP
\fBParameters\fP
.RS 4
\fIargs\fP System Line Arguments 
.RE
.PP

.SS "static void com\&.thealgorithms\&.maths\&.BinaryPow\&.test (int a, int p)\fC [static]\fP"
Function for testing binary exponentiation
.PP
\fBParameters\fP
.RS 4
\fIa\fP the base 
.br
\fIp\fP the exponent 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
