.TH "com.thealgorithms.maths.AliquotSum" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.AliquotSum
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static int \fBaliquotSum\fP (int number)"
.br
.in -1c
.SH "Detailed Description"
.PP 
In number theory, the aliquot sum s(n) of a positive integer n is the sum of all proper divisors of n, that is, all divisors of n other than n itself\&. For example, the proper divisors of 15 (that is, the positive divisors of 15 that are not equal to 15) are 1, 3 and 5, so the aliquot sum of 15 is 9 i\&.e\&. (1 + 3 + 5)\&. Wikipedia: https://en.wikipedia.org/wiki/Aliquot_sum 
.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.maths\&.AliquotSum\&.aliquotSum (int number)\fC [static]\fP"
Finds the aliquot sum of an integer number
.PP
\fBParameters\fP
.RS 4
\fInumber\fP a positive integer 
.RE
.PP
\fBReturns\fP
.RS 4
aliquot sum of given 
.PP
.nf
number 

.fi
.PP
 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
