.TH "com.thealgorithms.maths.AbsoluteMin" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.AbsoluteMin
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static int \fBabsMin\fP (int[] numbers)"
.br
.in -1c
.SH "Detailed Description"
.PP 
description:
.PP
absMin([0, 5, 1, 11]) = 0, absMin([3 , -10, -2]) = -2 
.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.maths\&.AbsoluteMin\&.absMin (int[] numbers)\fC [static]\fP"
get the value, returns the absolute min value min
.PP
\fBParameters\fP
.RS 4
\fInumbers\fP contains elements 
.RE
.PP
\fBReturns\fP
.RS 4
the absolute min value 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
