.TH "com.thealgorithms.searches.LinearSearch" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.searches.LinearSearch
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.thealgorithms\&.devutils\&.searches\&.SearchAlgorithm\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Linear search is the easiest search algorithm It works with sorted and unsorted arrays (an binary search works only with sorted array) This algorithm just compares all elements of an array to find a value
.PP
Worst-case performance O(n) Best-case performance O(1) Average performance O(n) Worst-case space complexity
.PP
\fBAuthor\fP
.RS 4
Varun Upadhyay (https://github.com/varunu28) 
.PP
Podshivalov Nikita (https://github.com/nikitap492) 
.RE
.PP
\fBSee also\fP
.RS 4
BinarySearch 
.PP
SearchAlgorithm 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
