.TH "com.thealgorithms.divideandconquer.StrassenMatrixMultiplication" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.divideandconquer.StrassenMatrixMultiplication
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int[][] \fBmultiply\fP (int[][] A, int[][] B)"
.br
.ti -1c
.RI "int[][] \fBsub\fP (int[][] A, int[][] B)"
.br
.ti -1c
.RI "int[][] \fBadd\fP (int[][] A, int[][] B)"
.br
.ti -1c
.RI "void \fBsplit\fP (int[][] P, int[][] C, int iB, int jB)"
.br
.ti -1c
.RI "void \fBjoin\fP (int[][] C, int[][] P, int iB, int jB)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
