.TH "com.thealgorithms.sorts.SortAlgorithm" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.sorts.SortAlgorithm
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBcom\&.thealgorithms\&.sorts\&.BogoSort\fP, com\&.thealgorithms\&.sorts\&.BubbleSort, \fBcom\&.thealgorithms\&.sorts\&.BubbleSortRecursion\fP, \fBcom\&.thealgorithms\&.sorts\&.CircleSort\fP, com\&.thealgorithms\&.sorts\&.CocktailShakerSort, com\&.thealgorithms\&.sorts\&.CombSort, com\&.thealgorithms\&.sorts\&.CountingSort, com\&.thealgorithms\&.sorts\&.CycleSort, \fBcom\&.thealgorithms\&.sorts\&.GnomeSort\fP, \fBcom\&.thealgorithms\&.sorts\&.HeapSort\fP, com\&.thealgorithms\&.sorts\&.InsertionSort, com\&.thealgorithms\&.sorts\&.MergeSort, \fBcom\&.thealgorithms\&.sorts\&.PancakeSort\fP, com\&.thealgorithms\&.sorts\&.QuickSort, \fBcom\&.thealgorithms\&.sorts\&.SelectionSort\fP, \fBcom\&.thealgorithms\&.sorts\&.ShellSort\fP, \fBcom\&.thealgorithms\&.sorts\&.SimpleSort\fP, \fBcom\&.thealgorithms\&.sorts\&.SlowSort\fP, \fBcom\&.thealgorithms\&.sorts\&.StoogeSort\fP, \fBcom\&.thealgorithms\&.sorts\&.SwapSort\fP, and \fBcom\&.thealgorithms\&.sorts\&.TreeSort\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "< T extends Comparable< T > T[] \fBsort\fP (T[] unsorted)"
.br
.ti -1c
.RI "default< T extends Comparable< T > > List< T > \fBsort\fP (List< T > unsorted)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The common interface of most sorting algorithms
.PP
\fBAuthor\fP
.RS 4
Podshivalov Nikita (https://github.com/nikitap492) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "default< T extends Comparable< T > > List< T > com\&.thealgorithms\&.sorts\&.SortAlgorithm\&.sort (List< T > unsorted)"
Auxiliary method for algorithms what wanted to work with lists from JCF
.PP
\fBParameters\fP
.RS 4
\fIunsorted\fP - a list should be sorted 
.RE
.PP
\fBReturns\fP
.RS 4
a sorted list 
.RE
.PP

.SS "< T extends Comparable< T > T[] com\&.thealgorithms\&.sorts\&.SortAlgorithm\&.sort (T[] unsorted)"
Main method arrays sorting algorithms
.PP
\fBParameters\fP
.RS 4
\fIunsorted\fP - an array should be sorted 
.RE
.PP
\fBReturns\fP
.RS 4
a sorted array 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
