.TH "com.thealgorithms.maths.FindMin" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.FindMin
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static int \fBfindMin\fP (int[] array)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.maths\&.FindMin\&.findMin (int[] array)\fC [static]\fP"
Find the minimum number of an array of numbers\&.
.PP
\fBParameters\fP
.RS 4
\fIarray\fP the array contains element 
.RE
.PP
\fBReturns\fP
.RS 4
min value 
.RE
.PP

.SS "static void com\&.thealgorithms\&.maths\&.FindMin\&.main (String[] args)\fC [static]\fP"
Driver Code 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
