.TH "com.thealgorithms.datastructures.trees.AVLTree" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.trees.AVLTree
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBinsert\fP (int key)"
.br
.ti -1c
.RI "void \fBdelete\fP (int delKey)"
.br
.ti -1c
.RI "void \fBprintBalance\fP ()"
.br
.ti -1c
.RI "boolean \fBsearch\fP (int key)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
