.TH "com.thealgorithms.maths.Convolution" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.Convolution
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double[] \fBconvolution\fP (double[] A, double[] B)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for linear convolution of two discrete signals
.PP
\fBAuthor\fP
.RS 4
Ioannis Karavitsis 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static double[] com\&.thealgorithms\&.maths\&.Convolution\&.convolution (double[] A, double[] B)\fC [static]\fP"
Discrete linear convolution function\&. Both input signals and the output signal must start from 0\&. If you have a signal that has values before 0 then shift it to start from 0\&.
.PP
\fBParameters\fP
.RS 4
\fIA\fP The first discrete signal 
.br
\fIB\fP The second discrete signal 
.RE
.PP
\fBReturns\fP
.RS 4
The convolved signal 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
