.TH "com.thealgorithms.sorts.BucketSort" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.sorts.BucketSort
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static int \fBmax\fP (int[] arr)"
.br
.ti -1c
.RI "static int \fBmin\fP (int[] arr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wikipedia: https://en.wikipedia.org/wiki/Bucket_sort 
.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.sorts\&.BucketSort\&.max (int[] arr)\fC [static]\fP"
Calculate max value of array
.PP
\fBParameters\fP
.RS 4
\fIarr\fP the array contains elements 
.RE
.PP
\fBReturns\fP
.RS 4
max value of given array 
.RE
.PP

.SS "static int com\&.thealgorithms\&.sorts\&.BucketSort\&.min (int[] arr)\fC [static]\fP"
Calculate min value of array
.PP
\fBParameters\fP
.RS 4
\fIarr\fP the array contains elements 
.RE
.PP
\fBReturns\fP
.RS 4
min value of given array 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
