.TH "com.thealgorithms.others.StringMatchFiniteAutomata" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.others.StringMatchFiniteAutomata
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static void \fBsearchPat\fP (String text, String pat)"
.br
.ti -1c
.RI "static void \fBcomputeFA\fP (String pat, int m, int[][] FA)"
.br
.ti -1c
.RI "static int \fBgetNextState\fP (String pat, int m, int state, int x)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final int \fBCHARS\fP = 256"
.br
.ti -1c
.RI "static int[][] \fBFA\fP"
.br
.ti -1c
.RI "static Scanner \fBscanner\fP = null"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
