.TH "com.thealgorithms.maths.PiNilakantha" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.PiNilakantha
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static double \fBcalculatePi\fP (int iterations)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static double com\&.thealgorithms\&.maths\&.PiNilakantha\&.calculatePi (int iterations)\fC [static]\fP"

.PP
\fBParameters\fP
.RS 4
\fIiterations\fP number of times the infinite series gets repeated Pi get more accurate the higher the value of iterations is Values from 0 up to 500 are allowed since double precision is not sufficient for more than about 500 repetitions of this algorithm 
.RE
.PP
\fBReturns\fP
.RS 4
the pi value of the calculation with a precision of x iteration 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
