.TH "com.thealgorithms.maths.ParseInteger" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.ParseInteger
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static int \fBparseInt\fP (String s)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.maths\&.ParseInteger\&.parseInt (String s)\fC [static]\fP"
Parse a string to integer
.PP
\fBParameters\fP
.RS 4
\fIs\fP the string 
.RE
.PP
\fBReturns\fP
.RS 4
the integer value represented by the argument in decimal\&. 
.RE
.PP
\fBExceptions\fP
.RS 4
\fINumberFormatException\fP if the 
.PP
.nf
string 

.fi
.PP
 does not contain a parsable integer\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
