.TH "com.thealgorithms.others.BFPRT" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.others.BFPRT
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int[] \fBgetMinKNumsByBFPRT\fP (int[] arr, int k)"
.br
.ti -1c
.RI "static int \fBgetMinKthByBFPRT\fP (int[] arr, int k)"
.br
.ti -1c
.RI "static int[] \fBcopyArray\fP (int[] arr)"
.br
.ti -1c
.RI "static int \fBbfprt\fP (int[] arr, int begin, int end, int i)"
.br
.ti -1c
.RI "static int \fBmedianOfMedians\fP (int[] arr, int begin, int end)"
.br
.ti -1c
.RI "static void \fBswap\fP (int[] arr, int i, int j)"
.br
.ti -1c
.RI "static int[] \fBpartition\fP (int[] arr, int begin, int end, int num)"
.br
.ti -1c
.RI "static int \fBgetMedian\fP (int[] arr, int begin, int end)"
.br
.ti -1c
.RI "static void \fBinsertionSort\fP (int[] arr, int begin, int end)"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBFPRT\fP algorithm\&. 
.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.others\&.BFPRT\&.medianOfMedians (int[] arr, int begin, int end)\fC [static]\fP"
wikipedia: https://en.wikipedia.org/wiki/Median_of_medians \&.
.PP
\fBParameters\fP
.RS 4
\fIarr\fP an array\&. 
.br
\fIbegin\fP begin num\&. 
.br
\fIend\fP end num\&. 
.RE
.PP
\fBReturns\fP
.RS 4
median of medians\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
