.TH "com.thealgorithms.datastructures.queues.LinkedQueue" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.queues.LinkedQueue
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNode\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinkedQueue\fP ()"
.br
.ti -1c
.RI "boolean \fBisEmpty\fP ()"
.br
.ti -1c
.RI "boolean \fBenqueue\fP (int data)"
.br
.ti -1c
.RI "int \fBdequeue\fP ()"
.br
.ti -1c
.RI "int \fBpeekFront\fP ()"
.br
.ti -1c
.RI "int \fBpeekRear\fP ()"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.thealgorithms\&.datastructures\&.queues\&.LinkedQueue\&.LinkedQueue ()"
Init \fBLinkedQueue\fP 
.SH "Member Function Documentation"
.PP 
.SS "void com\&.thealgorithms\&.datastructures\&.queues\&.LinkedQueue\&.clear ()"
Clear all nodes in queue 
.SS "int com\&.thealgorithms\&.datastructures\&.queues\&.LinkedQueue\&.dequeue ()"
Remove element at the front of queue
.PP
\fBReturns\fP
.RS 4
element at the front of queue 
.RE
.PP

.SS "boolean com\&.thealgorithms\&.datastructures\&.queues\&.LinkedQueue\&.enqueue (int data)"
Add element to rear of queue
.PP
\fBParameters\fP
.RS 4
\fIdata\fP insert value 
.RE
.PP
\fBReturns\fP
.RS 4
true if add successfully 
.RE
.PP

.SS "boolean com\&.thealgorithms\&.datastructures\&.queues\&.LinkedQueue\&.isEmpty ()"
Check if queue is empty
.PP
\fBReturns\fP
.RS 4
true if queue is empty, otherwise false 
.RE
.PP

.SS "int com\&.thealgorithms\&.datastructures\&.queues\&.LinkedQueue\&.peekFront ()"
Peek element at the front of queue without removing
.PP
\fBReturns\fP
.RS 4
element at the front 
.RE
.PP

.SS "int com\&.thealgorithms\&.datastructures\&.queues\&.LinkedQueue\&.peekRear ()"
Peek element at the rear of queue without removing
.PP
\fBReturns\fP
.RS 4
element at the front 
.RE
.PP

.SS "int com\&.thealgorithms\&.datastructures\&.queues\&.LinkedQueue\&.size ()"
Return size of queue
.PP
\fBReturns\fP
.RS 4
size of queue 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
