.TH "com.thealgorithms.conversions.TurkishToLatinConversion" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.conversions.TurkishToLatinConversion
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String args[])"
.br
.ti -1c
.RI "static String \fBconvertTurkishToLatin\fP (String param)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Converts turkish character to latin character
.PP
\fBAuthor\fP
.RS 4
Özgün Gökşenli 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static String com\&.thealgorithms\&.conversions\&.TurkishToLatinConversion\&.convertTurkishToLatin (String param)\fC [static]\fP"
This method converts a turkish character to latin character\&.
.PP
\fBParameters\fP
.RS 4
\fIparam\fP String paramter 
.RE
.PP
\fBReturns\fP
.RS 4
String 
.RE
.PP

.SS "static void com\&.thealgorithms\&.conversions\&.TurkishToLatinConversion\&.main (String args[])\fC [static]\fP"
Main method
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Command line arguments 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
