.TH "com.thealgorithms.maths.FibonacciNumber" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.FibonacciNumber
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static boolean \fBisPerfectSquare\fP (int number)"
.br
.ti -1c
.RI "static boolean \fBisFibonacciNumber\fP (int number)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Fibonacci: 0 1 1 2 3 5 8 13 21 \&.\&.\&. 
.SH "Member Function Documentation"
.PP 
.SS "static boolean com\&.thealgorithms\&.maths\&.FibonacciNumber\&.isFibonacciNumber (int number)\fC [static]\fP"
Check if a number is fibonacci number This is true if and only if at least one of 5x^2+4 or 5x^2-4 is a perfect square
.PP
\fBParameters\fP
.RS 4
\fInumber\fP the number 
.RE
.PP
\fBReturns\fP
.RS 4
\fCtrue\fP if 
.PP
.nf
number 

.fi
.PP
 is fibonacci number, otherwise \fCfalse\fP \fBhttps://en\&.wikipedia\&.org/wiki/Fibonacci_number#Identification\fP
.RE
.PP

.SS "static boolean com\&.thealgorithms\&.maths\&.FibonacciNumber\&.isPerfectSquare (int number)\fC [static]\fP"
Check if a number is perfect square number
.PP
\fBParameters\fP
.RS 4
\fInumber\fP the number to be checked 
.RE
.PP
\fBReturns\fP
.RS 4
\fCtrue\fP if 
.PP
.nf
number 

.fi
.PP
 is perfect square, otherwise \fCfalse\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
