.TH "com.thealgorithms.datastructures.graphs.BipartiteGrapfDFS" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.graphs.BipartiteGrapfDFS
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static boolean \fBisBipartite\fP (int V, ArrayList< ArrayList< Integer > > adj)"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)  throws IOException "
.br
.in -1c
.SH "Detailed Description"
.PP 
Given an adjacency list of a graph adj of V no\&. of vertices having 0 based index\&. Check whether the graph is bipartite or not\&.
.PP
Input : {{0, 1, 0, 1}, {1, 0, 1, 0}, {0, 1, 0, 1}, {1, 0, 1, 0}}
.PP
Output : YES 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
