.TH "com.thealgorithms.datastructures.trees.TrieImp" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.trees.TrieImp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTrieNode\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinsert\fP (String word)"
.br
.ti -1c
.RI "boolean \fBsearch\fP (String word)"
.br
.ti -1c
.RI "boolean \fBdelete\fP (String word)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsop\fP (String print)"
.br
.ti -1c
.RI "static boolean \fBisValid\fP (String word)"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static boolean com\&.thealgorithms\&.datastructures\&.trees\&.TrieImp\&.isValid (String word)\fC [static]\fP"
Regex to check if word contains only a-z character 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
