.TH "com.thealgorithms.maths.AutomorphicNumber" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.AutomorphicNumber
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static boolean \fBisAutomorphic\fP (int n)"
.br
.ti -1c
.RI "static void \fBmain\fP (String args[])  throws IOException "
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static boolean com\&.thealgorithms\&.maths\&.AutomorphicNumber\&.isAutomorphic (int n)\fC [static]\fP"
m = Temporary variable to store a copy of the number entered by the user\&. n = The number entered by the user c = Count the digits of the number entered by user\&. p = To calculate the square of the number\&. k = Support variable to count the digits of the number
.SS "static void com\&.thealgorithms\&.maths\&.AutomorphicNumber\&.main (String args[]) throws IOException\fC [static]\fP"
Method to check if number is Automorphic Number or Not 1) Input - Enter a Number: 25 Output - It is an Automorphic Number\&. 2) Input - Enter a Number: 7 Output - It is not an Automorphic Number\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
