.TH "com.thealgorithms.maths.DudeneyNumber" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.DudeneyNumber
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static boolean \fBisDudeney\fP (int n)"
.br
.ti -1c
.RI "static void \fBmain\fP (String args[])  throws IOException "
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.maths\&.DudeneyNumber\&.main (String args[]) throws IOException\fC [static]\fP"
Method to check if number is Dudeney Number or Not 1) Input - Enter a Number: 512 Output - It is a Dudeney Number\&. 2) Input - Enter a Number: 125 Output - It is not a Dudeney Number\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
