.TH "com.thealgorithms.dynamicprogramming.CoinChange" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.dynamicprogramming.CoinChange
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static int \fBchange\fP (int[] coins, int amount)"
.br
.ti -1c
.RI "static int \fBminimumCoins\fP (int[] coins, int amount)"
.br
.ti -1c
.RI "static void \fBprintAmount\fP (int[] arr)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Varun Upadhyay (https://github.com/varunu28) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.dynamicprogramming\&.CoinChange\&.change (int[] coins, int amount)\fC [static]\fP"
This method finds the number of combinations of getting change for a given amount and change coins
.PP
\fBParameters\fP
.RS 4
\fIcoins\fP The list of coins 
.br
\fIamount\fP The amount for which we need to find the change Finds the number of combinations of change 
.RE
.PP

.SS "static int com\&.thealgorithms\&.dynamicprogramming\&.CoinChange\&.minimumCoins (int[] coins, int amount)\fC [static]\fP"
This method finds the minimum number of coins needed for a given amount\&.
.PP
\fBParameters\fP
.RS 4
\fIcoins\fP The list of coins 
.br
\fIamount\fP The amount for which we need to find the minimum number of coins\&. Finds the the minimum number of coins that make a given value\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
