.TH "com.thealgorithms.dynamicprogramming.KadaneAlgorithm" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.dynamicprogramming.KadaneAlgorithm
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program to implement Kadane’s Algorithm to calculate maximum contiguous subarray sum of an array Time Complexity: O(n)
.PP
\fBAuthor\fP
.RS 4
Nishita Aggarwal 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.dynamicprogramming\&.KadaneAlgorithm\&.main (String[] args)\fC [static]\fP"
Main method
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Command line arguments 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
