.TH "com.thealgorithms.conversions.OctalToHexadecimal" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.conversions.OctalToHexadecimal
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBoctToDec\fP (String s)"
.br
.ti -1c
.RI "static String \fBdecimalToHex\fP (int d)"
.br
.ti -1c
.RI "static void \fBmain\fP (String args[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Converts any Octal Number to HexaDecimal
.PP
\fBAuthor\fP
.RS 4
Tanmay Joshi 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static String com\&.thealgorithms\&.conversions\&.OctalToHexadecimal\&.decimalToHex (int d)\fC [static]\fP"
This method converts a Decimal number to a Hexadecimal number
.PP
\fBParameters\fP
.RS 4
\fId\fP The Decimal Number 
.RE
.PP
\fBReturns\fP
.RS 4
The Hexadecimal number 
.RE
.PP

.SS "static int com\&.thealgorithms\&.conversions\&.OctalToHexadecimal\&.octToDec (String s)\fC [static]\fP"
This method converts a Octal number to a decimal number
.PP
\fBParameters\fP
.RS 4
\fIs\fP The Octal Number 
.RE
.PP
\fBReturns\fP
.RS 4
The Decimal number 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
