.TH "com.thealgorithms.maths.ADTFraction" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.ADTFraction
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBADTFraction\fP (int a, int b)"
.br
.ti -1c
.RI "void \fBset\fP (int a, int b)"
.br
.ti -1c
.RI "\fBADTFraction\fP \fBplus\fP (\fBADTFraction\fP x)"
.br
.ti -1c
.RI "\fBADTFraction\fP \fBtimes\fP (int a)"
.br
.ti -1c
.RI "\fBADTFraction\fP \fBtimes\fP (\fBADTFraction\fP x)"
.br
.ti -1c
.RI "\fBADTFraction\fP \fBreciprocal\fP ()"
.br
.ti -1c
.RI "float \fBvalue\fP ()"
.br
.ti -1c
.RI "void \fBdisplay\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
