.TH "com.thealgorithms.strings.Upper" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.strings.Upper
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static String \fBtoUpperCase\fP (String s)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.strings\&.Upper\&.main (String[] args)\fC [static]\fP"
Driver Code 
.SS "static String com\&.thealgorithms\&.strings\&.Upper\&.toUpperCase (String s)\fC [static]\fP"
Converts all of the characters in this 
.PP
.nf
String 

.fi
.PP
 to upper case
.PP
\fBParameters\fP
.RS 4
\fIs\fP the string to convert 
.RE
.PP
\fBReturns\fP
.RS 4
the 
.PP
.nf
String 

.fi
.PP
 , converted to uppercase\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
