.TH "com.thealgorithms.conversions.OctalToDecimal" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.conversions.OctalToDecimal
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String args[])"
.br
.ti -1c
.RI "static int \fBconvertOctalToDecimal\fP (String inputOctal)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Converts any Octal Number to a Decimal Number
.PP
\fBAuthor\fP
.RS 4
Zachary Jones 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.conversions\&.OctalToDecimal\&.convertOctalToDecimal (String inputOctal)\fC [static]\fP"
This method converts an octal number to a decimal number\&.
.PP
\fBParameters\fP
.RS 4
\fIinputOctal\fP The octal number 
.RE
.PP
\fBReturns\fP
.RS 4
The decimal number 
.RE
.PP

.SS "static void com\&.thealgorithms\&.conversions\&.OctalToDecimal\&.main (String args[])\fC [static]\fP"
Main method
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Command line arguments 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
