.TH "com.thealgorithms.datastructures.queues.PriorityQueues" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.queues.PriorityQueues
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class implements the PriorityQueue class above\&.
.PP
\fBAuthor\fP
.RS 4
Unknown 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.datastructures\&.queues\&.PriorityQueues\&.main (String[] args)\fC [static]\fP"
Main method
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Command Line Arguments 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
