.TH "com.thealgorithms.maths.Median" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.Median
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static double \fBmedian\fP (int[] values)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wikipedia: https://en.wikipedia.org/wiki/Median 
.SH "Member Function Documentation"
.PP 
.SS "static double com\&.thealgorithms\&.maths\&.Median\&.median (int[] values)\fC [static]\fP"
Calculate average median
.PP
\fBParameters\fP
.RS 4
\fIvalues\fP number series 
.RE
.PP
\fBReturns\fP
.RS 4
median of given 
.PP
.nf
values 

.fi
.PP
 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
