.TH "com.thealgorithms.maths.NumberOfDigits" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.NumberOfDigits
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Find the number of digits in a number\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
