.TH "com.thealgorithms.maths.PrimeCheck" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.PrimeCheck
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static boolean \fBisPrime\fP (int n)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static boolean com\&.thealgorithms\&.maths\&.PrimeCheck\&.isPrime (int n)\fC [static]\fP"

.IP "\(bu" 2
Checks if a number is prime or not
.PP
.PP
\fBParameters\fP
.RS 4
\fIn\fP the number 
.RE
.PP
\fBReturns\fP
.RS 4
.PP
.nf
true 
.fi
.PP
 if 
.PP
.nf
n 

.fi
.PP
 is prime 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
