.TH "com.thealgorithms.maths.Pow" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.Pow
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static long \fBpow\fP (int a, int b)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static long com\&.thealgorithms\&.maths\&.Pow\&.pow (int a, int b)\fC [static]\fP"
Returns the value of the first argument raised to the power of the second argument
.PP
\fBParameters\fP
.RS 4
\fIa\fP the base\&. 
.br
\fIb\fP the exponent\&. 
.RE
.PP
\fBReturns\fP
.RS 4
the value 
.PP
.nf
a 

.fi
.PP
 \*{
.PP
.nf
b 

.fi
.PP
 \*} \&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
