.TH "com.thealgorithms.sorts.TreeSort" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.sorts.TreeSort
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.thealgorithms\&.sorts\&.SortAlgorithm\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SH "Implementation of the Tree Sort algorithm"
.PP
.PP
Tree Sort: A sorting algorithm which constructs a Binary Search Tree using the unsorted data and then outputs the data by inorder traversal of the tree\&.
.PP
Reference: https://en.wikipedia.org/wiki/Tree_sort 
.PP
\fBAuthor\fP
.RS 4
Madhur Panwar (https://github.com/mdrpanwar) 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
