.TH "com.thealgorithms.misc.PalindromeSinglyLinkedList" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.misc.PalindromeSinglyLinkedList
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static boolean \fBisPalindrome\fP (\fBSinglyLinkedList\fP linkedList)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple way of knowing if a singly linked list is palindrome is to push all the values into a Stack and then compare the list to popped vales from the Stack\&.
.PP
See more: https://www.geeksforgeeks.org/function-to-check-if-a-singly-linked-list-is-palindrome/ 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
