.TH "com.thealgorithms.dynamicprogramming.LongestIncreasingSubsequence" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.dynamicprogramming.LongestIncreasingSubsequence
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static int \fBfindLISLen\fP (int a[])"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Afrizal Fikri (https://github.com/icalF) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.dynamicprogramming\&.LongestIncreasingSubsequence\&.findLISLen (int a[])\fC [static]\fP"

.PP
\fBAuthor\fP
.RS 4
Alon Firestein (https://github.com/alonfirestein) 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
