.TH "com.thealgorithms.strings.Anagrams" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.strings.Anagrams
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String args[])"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.strings\&.Anagrams\&.main (String args[])\fC [static]\fP"
OUTPUT : first string ='deal' second string ='lead' Output: Anagram Input and output is constant for all four approaches 1st approach Time Complexity : O(n logn) Auxiliary Space Complexity : O(1) 2nd approach Time Complexity : O(n) Auxiliary Space Complexity : O(1) 3rd approach Time Complexity : O(n) Auxiliary Space Complexity : O(1) 4th approach Time Complexity : O(n) Auxiliary Space Complexity : O(n)

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
