.TH "com.thealgorithms.strings.Pangram" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.strings.Pangram
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static boolean \fBisPangram\fP (String s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wikipedia: https://en.wikipedia.org/wiki/Pangram 
.SH "Member Function Documentation"
.PP 
.SS "static boolean com\&.thealgorithms\&.strings\&.Pangram\&.isPangram (String s)\fC [static]\fP"
Check if a string is a pangram string or not
.PP
\fBParameters\fP
.RS 4
\fIs\fP string to check 
.RE
.PP
\fBReturns\fP
.RS 4
.PP
.nf
true 
.fi
.PP
 if given string is pangram, otherwise 
.PP
.nf
false 

.fi
.PP
 
.RE
.PP

.SS "static void com\&.thealgorithms\&.strings\&.Pangram\&.main (String[] args)\fC [static]\fP"
Driver Code 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
