.TH "com.thealgorithms.dynamicprogramming.MinimumSumPartition" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.dynamicprogramming.MinimumSumPartition
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBsubSet\fP (int[] arr)"
.br
.ti -1c
.RI "static int \fBgetSum\fP (int[] arr)"
.br
.ti -1c
.RI "static int \fBgetMin\fP (int[] arr, int sum)"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.dynamicprogramming\&.MinimumSumPartition\&.getSum (int[] arr)\fC [static]\fP"
Calculate sum of array elements
.PP
\fBParameters\fP
.RS 4
\fIarr\fP the array 
.RE
.PP
\fBReturns\fP
.RS 4
sum of given array 
.RE
.PP

.SS "static void com\&.thealgorithms\&.dynamicprogramming\&.MinimumSumPartition\&.main (String[] args)\fC [static]\fP"
Driver Code 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
