.TH "com.thealgorithms.sorts.LinkList_Sort" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.sorts.LinkList_Sort
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static boolean \fBisSorted\fP (int p[], int option)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
