.TH "com.thealgorithms.datastructures.disjointsets.DisjointSets< T >" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.disjointsets.DisjointSets< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP< T > \fBMakeSet\fP (T x)"
.br
.ti -1c
.RI "\fBNode\fP< T > \fBFindSet\fP (\fBNode\fP< T > node)"
.br
.ti -1c
.RI "void \fBUnionSet\fP (\fBNode\fP< T > x, \fBNode\fP< T > y)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
