.TH "com.thealgorithms.datastructures.caches.MRUCache< K, V >" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.caches.MRUCache< K, V >
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEntry\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMRUCache\fP (int cap)"
.br
.ti -1c
.RI "V \fBget\fP (K key)"
.br
.ti -1c
.RI "void \fBput\fP (K key, V value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Most recently used (MRU) 
.PP
In contrast to Least Recently Used (LRU), MRU discards the most recently used items first\&. https://en.wikipedia.org/wiki/Cache_replacement_policies#Most_recently_used_(MRU)
.PP
\fBParameters\fP
.RS 4
\fI<K>\fP key type 
.br
\fI<V>\fP value type 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
