.TH "com.thealgorithms.sorts.GnomeSort" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.sorts.GnomeSort
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.thealgorithms\&.sorts\&.SortAlgorithm\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Implementation of gnome sort
.PP
\fBAuthor\fP
.RS 4
Podshivalov Nikita (https://github.com/nikitap492) 
.RE
.PP
\fBSince\fP
.RS 4
2018-04-10 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
