.TH "com.thealgorithms.maths.SumOfDigits" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.SumOfDigits
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static int \fBsumOfDigits\fP (int number)"
.br
.ti -1c
.RI "static int \fBsumOfDigitsRecursion\fP (int number)"
.br
.ti -1c
.RI "static int \fBsumOfDigitsFast\fP (int number)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.maths\&.SumOfDigits\&.sumOfDigits (int number)\fC [static]\fP"
Calculate the sum of digits of a number
.PP
\fBParameters\fP
.RS 4
\fInumber\fP the number contains digits 
.RE
.PP
\fBReturns\fP
.RS 4
sum of digits of given 
.PP
.nf
number 

.fi
.PP
 
.RE
.PP

.SS "static int com\&.thealgorithms\&.maths\&.SumOfDigits\&.sumOfDigitsFast (int number)\fC [static]\fP"
Calculate the sum of digits of a number using char array
.PP
\fBParameters\fP
.RS 4
\fInumber\fP the number contains digits 
.RE
.PP
\fBReturns\fP
.RS 4
sum of digits of given 
.PP
.nf
number 

.fi
.PP
 
.RE
.PP

.SS "static int com\&.thealgorithms\&.maths\&.SumOfDigits\&.sumOfDigitsRecursion (int number)\fC [static]\fP"
Calculate the sum of digits of a number using recursion
.PP
\fBParameters\fP
.RS 4
\fInumber\fP the number contains digits 
.RE
.PP
\fBReturns\fP
.RS 4
sum of digits of given 
.PP
.nf
number 

.fi
.PP
 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
