.TH "com.thealgorithms.maths.JugglerSequence" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.JugglerSequence
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBjugglerSequence\fP (int inputNumber)"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.maths\&.JugglerSequence\&.jugglerSequence (int inputNumber)\fC [static]\fP"
This method prints juggler sequence starting with the number in the parameter
.PP
\fBParameters\fP
.RS 4
\fIinputNumber\fP Number from which juggler sequence is to be started 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
