.TH "com.thealgorithms.maths.GCD" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.GCD
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBgcd\fP (int num1, int num2)"
.br
.ti -1c
.RI "static int \fBgcd\fP (int[] number)"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is Euclid's algorithm which is used to find the greatest common denominator Overide function name gcd
.PP
\fBAuthor\fP
.RS 4
Oskar Enmalm 3/10/17 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.maths\&.GCD\&.gcd (int num1, int num2)\fC [static]\fP"
get greatest common divisor
.PP
\fBParameters\fP
.RS 4
\fInum1\fP the first number 
.br
\fInum2\fP the second number 
.RE
.PP
\fBReturns\fP
.RS 4
gcd 
.RE
.PP

.SS "static int com\&.thealgorithms\&.maths\&.GCD\&.gcd (int[] number)\fC [static]\fP"
get greatest common divisor in array
.PP
\fBParameters\fP
.RS 4
\fInumber\fP contains number 
.RE
.PP
\fBReturns\fP
.RS 4
gcd 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
