.TH "com.thealgorithms.maths.HarshadNumber" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.HarshadNumber
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static void \fBcheckHarshadNumber\fP (long a)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.maths\&.HarshadNumber\&.checkHarshadNumber (long a)\fC [static]\fP"
A function to check if a number is Harshad number or not
.PP
\fBParameters\fP
.RS 4
\fIa\fP The number which should be checked 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
