.TH "com.thealgorithms.maths.FindMinRecursion" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.FindMinRecursion
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static int \fBmin\fP (int[] array, int low, int high)"
.br
.ti -1c
.RI "static int \fBmin\fP (int[] array, int len)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.maths\&.FindMinRecursion\&.main (String[] args)\fC [static]\fP"
Driver Code 
.SS "static int com\&.thealgorithms\&.maths\&.FindMinRecursion\&.min (int[] array, int len)\fC [static]\fP"
Get min of array using recursion algorithm
.PP
\fBParameters\fP
.RS 4
\fIarray\fP contains elements 
.br
\fIlen\fP length of given array 
.RE
.PP
\fBReturns\fP
.RS 4
min value of 
.PP
.nf
array 

.fi
.PP
 
.RE
.PP

.SS "static int com\&.thealgorithms\&.maths\&.FindMinRecursion\&.min (int[] array, int low, int high)\fC [static]\fP"
Get min of array using divide and conquer algorithm
.PP
\fBParameters\fP
.RS 4
\fIarray\fP contains elements 
.br
\fIlow\fP the index of the first element 
.br
\fIhigh\fP the index of the last element 
.RE
.PP
\fBReturns\fP
.RS 4
min of 
.PP
.nf
array 

.fi
.PP
 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
