.TH "com.thealgorithms.maths.MatrixUtil" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.MatrixUtil
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static boolean \fBisValid\fP (final BigDecimal[][] matrix)"
.br
.ti -1c
.RI "static boolean \fBhasEqualSizes\fP (final BigDecimal[][] matrix1, final BigDecimal[][] matrix2)"
.br
.ti -1c
.RI "static boolean \fBcanMultiply\fP (final BigDecimal[][] matrix1, final BigDecimal[][] matrix2)"
.br
.ti -1c
.RI "static Optional< BigDecimal[][]> \fBoperate\fP (final BigDecimal[][] matrix1, final BigDecimal[][] matrix2, final BiFunction< BigDecimal, BigDecimal, BigDecimal > operation)"
.br
.ti -1c
.RI "static Optional< BigDecimal[][]> \fBadd\fP (final BigDecimal[][] matrix1, final BigDecimal[][] matrix2)"
.br
.ti -1c
.RI "static Optional< BigDecimal[][]> \fBsubtract\fP (final BigDecimal[][] matrix1, final BigDecimal[][] matrix2)"
.br
.ti -1c
.RI "static Optional< BigDecimal[][]> \fBmultiply\fP (final BigDecimal[][] matrix1, final BigDecimal[][] matrix2)"
.br
.ti -1c
.RI "static void \fBassertThat\fP (final BigDecimal[][] actual, final BigDecimal[][] expected)"
.br
.ti -1c
.RI "static void \fBmain\fP (final String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
: caos321 
.RE
.PP
\fBDate\fP
.RS 4
: 31 October 2021 (Sunday) 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
