.TH "com.thealgorithms.maths.MinValue" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.MinValue
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static int \fBmin\fP (int a, int b)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.maths\&.MinValue\&.main (String[] args)\fC [static]\fP"
Driver Code 
.SS "static int com\&.thealgorithms\&.maths\&.MinValue\&.min (int a, int b)\fC [static]\fP"
Returns the smaller of two 
.PP
.nf
int 

.fi
.PP
 values\&. That is, the result the argument closer to the value of \fBInteger#MIN_VALUE\fP\&. If the arguments have the same value, the result is that same value\&.
.PP
\fBParameters\fP
.RS 4
\fIa\fP an argument\&. 
.br
\fIb\fP another argument\&. 
.RE
.PP
\fBReturns\fP
.RS 4
the smaller of 
.PP
.nf
a 

.fi
.PP
 and 
.PP
.nf
b 

.fi
.PP
 \&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
