.TH "com.thealgorithms.others.LowestBasePalindrome" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.others.LowestBasePalindrome
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static int \fBlowestBasePalindrome\fP (int num)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for finding the lowest base in which a given integer is a palindrome\&. Includes auxiliary methods for converting between bases and reversing strings\&.
.PP
NOTE: There is potential for error, see note at line 63\&.
.PP
\fBAuthor\fP
.RS 4
RollandMichael 
.RE
.PP
\fBVersion\fP
.RS 4
2017\&.09\&.28 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.others\&.LowestBasePalindrome\&.lowestBasePalindrome (int num)\fC [static]\fP"
Given a number in base 10, returns the lowest base in which the number is represented by a palindrome (read the same left-to-right and right-to-left)\&.
.PP
\fBParameters\fP
.RS 4
\fInum\fP A number in base 10\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The lowest base in which num is a palindrome\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
