.TH "com.thealgorithms.maths.PerfectCube" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.PerfectCube
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static boolean \fBisPerfectCube\fP (int number)"
.br
.in -1c
.SH "Detailed Description"
.PP 
https://en.wikipedia.org/wiki/Cube_(algebra) 
.SH "Member Function Documentation"
.PP 
.SS "static boolean com\&.thealgorithms\&.maths\&.PerfectCube\&.isPerfectCube (int number)\fC [static]\fP"
Check if a number is perfect cube or not
.PP
\fBParameters\fP
.RS 4
\fInumber\fP number to check 
.RE
.PP
\fBReturns\fP
.RS 4
.PP
.nf
true 
.fi
.PP
 if 
.PP
.nf
number 

.fi
.PP
 is perfect cube, otherwise 
.PP
.nf
false 

.fi
.PP
 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
