.TH "com.thealgorithms.others.RemoveDuplicateFromString" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.others.RemoveDuplicateFromString
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)  throws Exception "
.br
.ti -1c
.RI "static String \fBremoveDuplicate\fP (String s)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Varun Upadhyay (https://github.com/varunu28) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static String com\&.thealgorithms\&.others\&.RemoveDuplicateFromString\&.removeDuplicate (String s)\fC [static]\fP"
This method produces a string after removing all the duplicate characters from input string and returns it Example: Input String - 'aabbbccccddddd' Output String - 'abcd'
.PP
\fBParameters\fP
.RS 4
\fIs\fP String from which duplicate characters have to be removed 
.RE
.PP
\fBReturns\fP
.RS 4
string with only unique characters 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
