.TH "com.thealgorithms.datastructures.queues.CircularQueue" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.queues.CircularQueue
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCircularQueue\fP (int size)"
.br
.ti -1c
.RI "boolean \fBisEmpty\fP ()"
.br
.ti -1c
.RI "boolean \fBisFull\fP ()"
.br
.ti -1c
.RI "void \fBenQueue\fP (int value)"
.br
.ti -1c
.RI "int \fBdeQueue\fP ()"
.br
.ti -1c
.RI "int \fBpeek\fP ()"
.br
.ti -1c
.RI "void \fBdeleteQueue\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
