.TH "com.thealgorithms.datastructures.lists.RemoveDuplicateNodes" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.lists.RemoveDuplicateNodes
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Node \fBdeleteDuplicates\fP (Node head)"
.br
.ti -1c
.RI "void \fBprint\fP (Node head)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String arg[])"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
