.TH "com.thealgorithms.others.FibbonaciSeries" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.others.FibbonaciSeries
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Fibonacci sequence, and characterized by the fact that every number after the first two is the sum of the two preceding ones\&.
.PP
Fibonacci sequence: 0, 1, 1, 2, 3, 5, 8, 13, 21,\&.\&.\&.
.PP
Source for the explanation: https://en.wikipedia.org/wiki/Fibonacci_number
.PP
Problem Statement: print all Fibonacci numbers that are smaller than your given input N 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
