.TH "com.thealgorithms.datastructures.lists.SearchSinglyLinkedListRecursion" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.lists.SearchSinglyLinkedListRecursion
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.thealgorithms\&.datastructures\&.lists\&.SinglyLinkedList\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBsearch\fP (int key)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.datastructures\&.lists\&.SearchSinglyLinkedListRecursion\&.main (String[] arg)\fC [static]\fP"
Driver Code 
.PP
Reimplemented from \fBcom\&.thealgorithms\&.datastructures\&.lists\&.SinglyLinkedList\fP\&.
.SS "boolean com\&.thealgorithms\&.datastructures\&.lists\&.SearchSinglyLinkedListRecursion\&.search (int key)"
Test if the value key is present in the list\&.
.PP
\fBParameters\fP
.RS 4
\fIkey\fP the value to be searched\&. 
.RE
.PP
\fBReturns\fP
.RS 4
.PP
.nf
true 
.fi
.PP
 if key is present in the list, otherwise 
.PP
.nf
false 

.fi
.PP
 \&. 
.RE
.PP

.PP
Reimplemented from \fBcom\&.thealgorithms\&.datastructures\&.lists\&.SinglyLinkedList\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
