.TH "com.thealgorithms.maths.ConvolutionFFT" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.ConvolutionFFT
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static ArrayList< FFT\&.Complex > \fBconvolutionFFT\fP (ArrayList< FFT\&.Complex > a, ArrayList< FFT\&.Complex > b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for linear convolution of two discrete signals using the convolution theorem\&.
.PP
\fBAuthor\fP
.RS 4
Ioannis Karavitsis 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static ArrayList< FFT\&.Complex > com\&.thealgorithms\&.maths\&.ConvolutionFFT\&.convolutionFFT (ArrayList< FFT\&.Complex > a, ArrayList< FFT\&.Complex > b)\fC [static]\fP"
Discrete linear convolution function\&. It uses the convolution theorem for discrete signals convolved: = IDFT(DFT(a)*DFT(b))\&. This is true for circular convolution\&. In order to get the linear convolution of the two signals we first pad the two signals to have the same size equal to the convolved signal (a\&.size() + b\&.size() - 1)\&. Then we use the \fBFFT\fP algorithm for faster calculations of the two DFTs and the final IDFT\&.
.PP
More info: https://en.wikipedia.org/wiki/Convolution_theorem https://ccrma.stanford.edu/~jos/ReviewFourier/FFT_Convolution.html
.PP
\fBParameters\fP
.RS 4
\fIa\fP The first signal\&. 
.br
\fIb\fP The other signal\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The convolved signal\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
