.TH "com.thealgorithms.strings.ReverseString" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.strings.ReverseString
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static String \fBreverse\fP (String str)"
.br
.ti -1c
.RI "static String \fBreverse2\fP (String str)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reverse String using different version 
.SH "Member Function Documentation"
.PP 
.SS "static String com\&.thealgorithms\&.strings\&.ReverseString\&.reverse (String str)\fC [static]\fP"
easiest way to reverses the string str and returns it
.PP
\fBParameters\fP
.RS 4
\fIstr\fP string to be reversed 
.RE
.PP
\fBReturns\fP
.RS 4
reversed string 
.RE
.PP

.SS "static String com\&.thealgorithms\&.strings\&.ReverseString\&.reverse2 (String str)\fC [static]\fP"
second way to reverses the string str and returns it
.PP
\fBParameters\fP
.RS 4
\fIstr\fP string to be reversed 
.RE
.PP
\fBReturns\fP
.RS 4
reversed string 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
