.TH "com.thealgorithms.maths.Factorial" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.Factorial
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static long \fBfactorial\fP (int n)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static long com\&.thealgorithms\&.maths\&.Factorial\&.factorial (int n)\fC [static]\fP"
Calculate factorial N using iteration
.PP
\fBParameters\fP
.RS 4
\fIn\fP the number 
.RE
.PP
\fBReturns\fP
.RS 4
the factorial of 
.PP
.nf
n 

.fi
.PP
 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
