.TH "com.thealgorithms.dynamicprogramming.WineProblem" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.dynamicprogramming.WineProblem
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBWPRecursion\fP (int[] arr, int si, int ei)"
.br
.ti -1c
.RI "static int \fBWPTD\fP (int[] arr, int si, int ei, int[][] strg)"
.br
.ti -1c
.RI "static int \fBWPBU\fP (int[] arr)"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Imagine you have a collection of N wines placed next to each other on the shelf\&. The price of ith wine is pi(Prices of different wines are different)\&. Because wine gets better every year supposing today is year 1, on year y the price would be y*pi i\&.e y times the value of the initial year\&. You want to sell all wines but you have to sell one wine per year\&. One more constraint on each year you are allowed to sell either leftmost or rightmost wine on the shelf\&. You are not allowed to reorder\&. You have to find the maximum profit 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
