.TH "com.thealgorithms.maths.Floor" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.Floor
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static double \fBfloor\fP (double number)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static double com\&.thealgorithms\&.maths\&.Floor\&.floor (double number)\fC [static]\fP"
Returns the largest (closest to positive infinity)
.PP
\fBParameters\fP
.RS 4
\fInumber\fP the number 
.RE
.PP
\fBReturns\fP
.RS 4
the largest (closest to positive infinity) of given 
.PP
.nf
number 

.fi
.PP
 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
