.TH "com.thealgorithms.datastructures.trees.CreateBSTFromSortedArray" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.trees.CreateBSTFromSortedArray
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Given a sorted array\&. Create a balanced binary search tree from it\&.
.PP
Steps: 1\&. Find the middle element of array\&. This will act as root 2\&. Use the left half recursively to create left subtree 3\&. Use the right half recursively to create right subtree 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
