.TH "com.thealgorithms.searches.SquareRootBinarySearch" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.searches.SquareRootBinarySearch
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String args[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Given an integer x, find the square root of x\&. If x is not a perfect square, then return floor(√x)\&. 
.PP
For example, if x = 5, The answer should be 2 which is the floor value of √5\&. 
.PP
The approach that will be used for solving the above problem is not going to be a straight forward Math\&.sqrt()\&. Instead we will be using Binary Search to find the square root of a number in the most optimised way\&.
.PP
\fBAuthor\fP
.RS 4
sahil 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.searches\&.SquareRootBinarySearch\&.main (String args[])\fC [static]\fP"
This is the driver method\&.
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Command line arguments 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
