.TH "com.thealgorithms.others.KMP" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.others.KMP
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static void \fBKMPmatcher\fP (final String haystack, final String needle)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of Knuth–Morris–Pratt algorithm Usage: see the main function for an example 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
