.TH "com.thealgorithms.maths.AmicableNumber" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.AmicableNumber
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Amicable numbers are two different numbers so related that the sum of the proper divisors of each is equal to the other number\&. (A proper divisor of a number is a positive factor of that number other than the number itself\&. For example, the proper divisors of 6 are 1, 2, and 3\&.) A pair of amicable numbers constitutes an aliquot sequence of period 2\&. It is unknown if there are infinitely many pairs of amicable numbers\&. *
.PP
link: https://en.wikipedia.org/wiki/Amicable_numbers *
.PP
Simple Example : (220,284) 220 is divisible by {1,2,4,5,10,11,20,22,44,55,110 } <- Sum = 284 284 is divisible by -> 1,2,4,71,142 and the Sum of that is\&. Yes right you probably expected it 220 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
