.TH "com.thealgorithms.maths.PowerOfTwoOrNot" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.PowerOfTwoOrNot
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static boolean \fBcheckIfPowerOfTwoOrNot\fP (int number)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A utility to check if a given number is power of two or not\&. For example 8,16 etc\&. 
.SH "Member Function Documentation"
.PP 
.SS "static boolean com\&.thealgorithms\&.maths\&.PowerOfTwoOrNot\&.checkIfPowerOfTwoOrNot (int number)\fC [static]\fP"
Checks whether given number is power of two or not\&.
.PP
\fBParameters\fP
.RS 4
\fInumber\fP the number to check 
.RE
.PP
\fBReturns\fP
.RS 4
.PP
.nf
true 
.fi
.PP
 if given number is power of two, otherwise 
.PP
.nf
false 

.fi
.PP
 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
