.TH "com.thealgorithms.maths.PythagoreanTriple" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.PythagoreanTriple
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static boolean \fBisPythagTriple\fP (int a, int b, int c)"
.br
.in -1c
.SH "Detailed Description"
.PP 
https://en.wikipedia.org/wiki/Pythagorean_triple 
.SH "Member Function Documentation"
.PP 
.SS "static boolean com\&.thealgorithms\&.maths\&.PythagoreanTriple\&.isPythagTriple (int a, int b, int c)\fC [static]\fP"
Check if a,b,c are a Pythagorean Triple
.PP
\fBParameters\fP
.RS 4
\fIa\fP x/y component length of a right triangle 
.br
\fIb\fP y/x component length of a right triangle 
.br
\fIc\fP hypotenuse length of a right triangle 
.RE
.PP
\fBReturns\fP
.RS 4
boolean \fCtrue\fP if a, b, c satisfy the Pythagorean theorem, otherwise \fCfalse\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
