.TH "com.thealgorithms.others.BestFit" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.others.BestFit
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBprintMemoryAllocation\fP (ArrayList< Integer > memAllocation)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Dekas Dimitrios 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.others\&.BestFit\&.printMemoryAllocation (ArrayList< Integer > memAllocation)\fC [static]\fP"
Method to print the memory allocated\&.
.PP
\fBParameters\fP
.RS 4
\fImemAllocation\fP an ArrayList of Integer representing the memory allocation done by the bestFit method\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
