.TH "com.thealgorithms.maths.KrishnamurthyNumber" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.KrishnamurthyNumber
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static boolean \fBisKMurthy\fP (int n)"
.br
.ti -1c
.RI "static void \fBmain\fP (String args[])  throws IOException "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
