.TH "com.thealgorithms.datastructures.lists.CountSinglyLinkedListRecursion" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.lists.CountSinglyLinkedListRecursion
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.thealgorithms\&.datastructures\&.lists\&.SinglyLinkedList\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBcount\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int com\&.thealgorithms\&.datastructures\&.lists\&.CountSinglyLinkedListRecursion\&.count ()"
Returns the count of the list\&. 
.PP
Reimplemented from \fBcom\&.thealgorithms\&.datastructures\&.lists\&.SinglyLinkedList\fP\&.
.SS "static void com\&.thealgorithms\&.datastructures\&.lists\&.CountSinglyLinkedListRecursion\&.main (String[] arg)\fC [static]\fP"
Driver Code 
.PP
Reimplemented from \fBcom\&.thealgorithms\&.datastructures\&.lists\&.SinglyLinkedList\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
