.TH "com.thealgorithms.maths.RomanNumeralUtil" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.RomanNumeralUtil
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static String \fBgenerate\fP (int number)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Translates numbers into the Roman Numeral System\&.
.PP
\fBSee also\fP
.RS 4
\fCRoman numerals\fP 
.RE
.PP
\fBAuthor\fP
.RS 4
Sokratis Fotkatzikis 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
