.TH "com.thealgorithms.datastructures.lists" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.lists
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCircleLinkedList\fP"
.br
.ti -1c
.RI "class \fBCountSinglyLinkedListRecursion\fP"
.br
.ti -1c
.RI "class \fBCreateAndDetectLoop\fP"
.br
.ti -1c
.RI "class \fBCursorLinkedList\fP"
.br
.ti -1c
.RI "class \fBDoublyLinkedList\fP"
.br
.ti -1c
.RI "class \fBLink\fP"
.br
.ti -1c
.RI "class \fBMerge_K_SortedLinkedlist\fP"
.br
.ti -1c
.RI "class \fBMergeSortedArrayList\fP"
.br
.ti -1c
.RI "class \fBMergeSortedSinglyLinkedList\fP"
.br
.ti -1c
.RI "class \fBNode\fP"
.br
.ti -1c
.RI "class \fBRandomNode\fP"
.br
.ti -1c
.RI "class \fBRemoveDuplicateNodes\fP"
.br
.ti -1c
.RI "class \fBSearchSinglyLinkedListRecursion\fP"
.br
.ti -1c
.RI "class \fBSinglyLinkedList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Author : Suraj Kumar Github : https://github.com/skmodi649 PROBLEM DESCRIPTION : There is a single linked list and we are supposed to find a random node in the given linked list ALGORITHM : Step 1 : START Step 2 : Create an arraylist of type integer Step 3 : Declare an integer type variable for size and linked list type for head Step 4 : We will use two methods, one for traversing through the linked list using while loop and also increase the size by 1
.PP
(a) RandomNode(head) (b) run a while loop till null; (c) add the value to arraylist; (d) increase the size;
.PP
Step 5 : Now use another method for getting random values using Math\&.random() and return the value present in arraylist for the calculated index Step 6 : Now in main() method we will simply insert nodes in the linked list and then call the appropriate method and then print the random node generated Step 7 : STOP 
.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
