.TH "com.thealgorithms.backtracking.NQueens" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.backtracking.NQueens
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static void \fBplaceQueens\fP (final int queens)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Problem statement: Given a N x N chess board\&. Return all arrangements in which N queens can be placed on the board such no two queens attack each other\&. Ex\&. N = 6 Solution= There are 4 possible ways Arrangement: 1 '\&.Q\&.\&.\&.\&.', '\&.\&.\&.Q\&.\&.', '\&.\&.\&.\&.\&.Q', 'Q\&.\&.\&.\&.\&.', '\&.\&.Q\&.\&.\&.', '\&.\&.\&.\&.Q\&.' 
.PP
Arrangement: 2 '\&.\&.Q\&.\&.\&.', '\&.\&.\&.\&.\&.Q', '\&.Q\&.\&.\&.\&.', '\&.\&.\&.\&.Q\&.', 'Q\&.\&.\&.\&.\&.', '\&.\&.\&.Q\&.\&.' 
.PP
Arrangement: 3 '\&.\&.\&.Q\&.\&.', 'Q\&.\&.\&.\&.\&.', '\&.\&.\&.\&.Q\&.', '\&.Q\&.\&.\&.\&.', '\&.\&.\&.\&.\&.Q', '\&.\&.Q\&.\&.\&.' 
.PP
Arrangement: 4 '\&.\&.\&.\&.Q\&.', '\&.\&.Q\&.\&.\&.', 'Q\&.\&.\&.\&.\&.', '\&.\&.\&.\&.\&.Q', '\&.\&.\&.Q\&.\&.', '\&.Q\&.\&.\&.\&.'
.PP
Solution: Brute Force approach:
.PP
Generate all possible arrangement to place N queens on N*N board\&. Check each board if queens are placed safely\&. If it is safe, include arrangement in solution set\&. Otherwise ignore it
.PP
Optimized solution: This can be solved using backtracking in below steps
.PP
Start with first column and place queen on first row Try placing queen in a row on second column If placing second queen in second column attacks any of the previous queens, change the row in second column otherwise move to next column and try to place next queen In case if there is no rows where a queen can be placed such that it doesn't attack previous queens, then go back to previous column and change row of previous queen\&. Keep doing this until last queen is not placed safely\&. If there is no such way then return an empty list as solution 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
