.TH "com.thealgorithms.conversions.DecimalToOctal" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.conversions.DecimalToOctal
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class converts Decimal numbers to Octal Numbers 
.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.conversions\&.DecimalToOctal\&.main (String[] args)\fC [static]\fP"
Main Method
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Command line Arguments 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
