.TH "com.thealgorithms.matrixexponentiation.Fibonacci" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.matrixexponentiation.Fibonacci
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int[][] \fBfib\fP (int n)"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Anirudh Buvanesh (https://github.com/anirudhb11) For more information see https://www.geeksforgeeks.org/matrix-exponentiation/ 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static int[][] com\&.thealgorithms\&.matrixexponentiation\&.Fibonacci\&.fib (int n)\fC [static]\fP"
Calculates the fibonacci number using matrix exponentiaition technique
.PP
\fBParameters\fP
.RS 4
\fIn\fP The input n for which we have to determine the fibonacci number Outputs the nth * fibonacci number 
.RE
.PP
\fBReturns\fP
.RS 4
a 2 X 1 array as { {F_n+1}, {F_n} } 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
