.TH "com.thealgorithms.maths.AbsoluteValue" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.AbsoluteValue
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static int \fBabsVal\fP (int value)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.maths\&.AbsoluteValue\&.absVal (int value)\fC [static]\fP"
If value is less than zero, make value positive\&.
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP a number 
.RE
.PP
\fBReturns\fP
.RS 4
the absolute value of a number 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
