.TH "com.thealgorithms.datastructures.lists.RandomNode" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.lists.RandomNode
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBListNode\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandomNode\fP (ListNode head)"
.br
.ti -1c
.RI "int \fBgetRandom\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
