.TH "com.thealgorithms.maths.SumOfArithmeticSeries" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.SumOfArithmeticSeries
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
In mathematics, an arithmetic progression (AP) or arithmetic sequence is a sequence of numbers such that the difference between the consecutive terms is constant\&. Difference here means the second minus the first\&. For instance, the sequence 5, 7, 9, 11, 13, 15, \&. \&. \&. is an arithmetic progression with common difference of 2\&.
.PP
Wikipedia: https://en.wikipedia.org/wiki/Arithmetic_progression 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
