.TH "com.thealgorithms.misc.InverseOfMatrix" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.misc.InverseOfMatrix
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String argv[])"
.br
.ti -1c
.RI "static double[][] \fBinvert\fP (double a[][])"
.br
.ti -1c
.RI "static void \fBgaussian\fP (double a[][], int index[])"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
