.TH "com.thealgorithms.devutils.nodes.Node< E >" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.devutils.nodes.Node< E >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBcom\&.thealgorithms\&.devutils\&.nodes\&.SimpleNode< E >\fP, and \fBcom\&.thealgorithms\&.devutils\&.nodes\&.TreeNode< E >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP ()"
.br
.ti -1c
.RI "\fBNode\fP (E data)"
.br
.ti -1c
.RI "E \fBgetData\fP ()"
.br
.ti -1c
.RI "void \fBsetData\fP (E data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for any node implementation which contains a generic type variable\&.
.PP
All known subclasses: \fBTreeNode\fP, \fBSimpleNode\fP\&.
.PP
\fBParameters\fP
.RS 4
\fI<E>\fP The type of the data held in the \fBNode\fP\&.
.RE
.PP
\fBAuthor\fP
.RS 4
\fCaitorfi\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBcom\&.thealgorithms\&.devutils\&.nodes\&.Node\fP< E >\&.\fBNode\fP ()"
Empty constructor\&. 
.SS "\fBcom\&.thealgorithms\&.devutils\&.nodes\&.Node\fP< E >\&.\fBNode\fP (E data)"
Initializes the Nodes' data\&.
.PP
\fBParameters\fP
.RS 4
\fIdata\fP Value to which data will be initialized\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
