.TH "com.thealgorithms.datastructures.lists.Merge_K_SortedLinkedlist" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.lists.Merge_K_SortedLinkedlist
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Arun Pandey (https://github.com/pandeyarun709) 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
