.TH "com.thealgorithms.maths.PerfectSquare" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.PerfectSquare
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static boolean \fBisPerfectSquare\fP (int number)"
.br
.in -1c
.SH "Detailed Description"
.PP 
https://en.wikipedia.org/wiki/Perfect_square 
.SH "Member Function Documentation"
.PP 
.SS "static boolean com\&.thealgorithms\&.maths\&.PerfectSquare\&.isPerfectSquare (int number)\fC [static]\fP"
Check if a number is perfect square number
.PP
\fBParameters\fP
.RS 4
\fInumber\fP the number to be checked 
.RE
.PP
\fBReturns\fP
.RS 4
\fCtrue\fP if 
.PP
.nf
number 

.fi
.PP
 is perfect square, otherwise \fCfalse\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
