.TH "com.thealgorithms.conversions.RomanToInteger" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.conversions.RomanToInteger
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBromanToInt\fP (String A)"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.conversions\&.RomanToInteger\&.romanToInt (String A)\fC [static]\fP"
This function convert Roman number into Integer
.PP
\fBParameters\fP
.RS 4
\fIA\fP Roman number string 
.RE
.PP
\fBReturns\fP
.RS 4
integer 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
