.TH "com.thealgorithms.datastructures.trees.FenwickTree" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.trees.FenwickTree
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFenwickTree\fP (int n)"
.br
.ti -1c
.RI "void \fBupdate\fP (int i, int val)"
.br
.ti -1c
.RI "int \fBquery\fP (int i)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
