.TH "com.thealgorithms.sorts.HeapSort" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.sorts.HeapSort
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.thealgorithms\&.sorts\&.SortAlgorithm\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Heap Sort Algorithm Implements MinHeap
.PP
\fBAuthor\fP
.RS 4
Podshivalov Nikita (https://github.com/nikitap492) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.sorts\&.HeapSort\&.main (String[] args)\fC [static]\fP"
Main method
.PP
\fBParameters\fP
.RS 4
\fIargs\fP the command line arguments 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
