.TH "com.thealgorithms.others.EulersFunction" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.others.EulersFunction
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBgetEuler\fP (int n)"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
You can read more about Euler's totient function
.PP
See https://en.wikipedia.org/wiki/Euler%27s_totient_function 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
