.TH "com.thealgorithms.datastructures.lists.MergeSortedArrayList" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.lists.MergeSortedArrayList
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static void \fBmerge\fP (List< Integer > listA, List< Integer > listB, List< Integer > listC)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
https://github.com/shellhub 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.datastructures\&.lists\&.MergeSortedArrayList\&.merge (List< Integer > listA, List< Integer > listB, List< Integer > listC)\fC [static]\fP"
merge two sorted ArrayList
.PP
\fBParameters\fP
.RS 4
\fIlistA\fP the first list to merge 
.br
\fIlistB\fP the second list to merge 
.br
\fIlistC\fP the result list after merging 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
