.TH "com.thealgorithms.misc.RangeInSortedArray" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.misc.RangeInSortedArray
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static int[] \fBsortedRange\fP (int[] nums, int key)"
.br
.ti -1c
.RI "static void \fBalteredBinSearch\fP (int[] nums, int key, int left, int right, int[] range, boolean goLeft)"
.br
.ti -1c
.RI "static void \fBalteredBinSearchIter\fP (int[] nums, int key, int left, int right, int[] range, boolean goLeft)"
.br
.ti -1c
.RI "static int \fBgetCountLessThan\fP (int[] nums, int key)"
.br
.ti -1c
.RI "static int \fBgetLessThan\fP (int[] nums, int key, int left, int right)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
