.TH "com.thealgorithms.conversions.DecimalToAnyBase" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.conversions.DecimalToAnyBase
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)  throws Exception "
.br
.ti -1c
.RI "static String \fBconvertToAnyBase\fP (int inp, int base)"
.br
.ti -1c
.RI "static char \fBreVal\fP (int num)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Varun Upadhyay (https://github.com/varunu28) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static String com\&.thealgorithms\&.conversions\&.DecimalToAnyBase\&.convertToAnyBase (int inp, int base)\fC [static]\fP"
This method produces a String value of any given input decimal in any base
.PP
\fBParameters\fP
.RS 4
\fIinp\fP Decimal of which we need the value in base in String format 
.RE
.PP
\fBReturns\fP
.RS 4
string format of the converted value in the given base 
.RE
.PP

.SS "static char com\&.thealgorithms\&.conversions\&.DecimalToAnyBase\&.reVal (int num)\fC [static]\fP"
This method produces character value of the input integer and returns it
.PP
\fBParameters\fP
.RS 4
\fInum\fP integer of which we need the character value of 
.RE
.PP
\fBReturns\fP
.RS 4
character value of input integer 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
