.TH "com.thealgorithms.maths.FactorialRecursion" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.FactorialRecursion
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static long \fBfactorial\fP (int n)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static long com\&.thealgorithms\&.maths\&.FactorialRecursion\&.factorial (int n)\fC [static]\fP"
Recursive \fBFactorialRecursion\fP Method
.PP
\fBParameters\fP
.RS 4
\fIn\fP The number to factorial 
.RE
.PP
\fBReturns\fP
.RS 4
The factorial of the number 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
