.TH "com.thealgorithms.sorts" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.sorts
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApp\fP"
.br
.ti -1c
.RI "class \fBBitonicSort\fP"
.br
.ti -1c
.RI "class \fBBogoSort\fP"
.br
.ti -1c
.RI "class \fBBubbleSort\fP"
.br
.ti -1c
.RI "class \fBBubbleSortRecursion\fP"
.br
.ti -1c
.RI "class \fBBucketSort\fP"
.br
.ti -1c
.RI "class \fBCircleSort\fP"
.br
.ti -1c
.RI "class \fBCocktailShakerSort\fP"
.br
.ti -1c
.RI "class \fBCombSort\fP"
.br
.ti -1c
.RI "class \fBCountingSort\fP"
.br
.ti -1c
.RI "class \fBCycleSort\fP"
.br
.ti -1c
.RI "class \fBDNFSort\fP"
.br
.ti -1c
.RI "class \fBGnomeSort\fP"
.br
.ti -1c
.RI "class \fBHeapSort\fP"
.br
.ti -1c
.RI "class \fBInsertionSort\fP"
.br
.ti -1c
.RI "class \fBLinkList_Sort\fP"
.br
.ti -1c
.RI "class \fBMergeSort\fP"
.br
.ti -1c
.RI "class \fBMergeSortNoExtraSpace\fP"
.br
.ti -1c
.RI "class \fBMergeSortRecursive\fP"
.br
.ti -1c
.RI "class \fBNode\fP"
.br
.ti -1c
.RI "class \fBOddEvenSort\fP"
.br
.ti -1c
.RI "class \fBPancakeSort\fP"
.br
.ti -1c
.RI "class \fBQuickSort\fP"
.br
.ti -1c
.RI "class \fBRadixSort\fP"
.br
.ti -1c
.RI "class \fBSelectionSort\fP"
.br
.ti -1c
.RI "class \fBShellSort\fP"
.br
.ti -1c
.RI "class \fBSimpleSort\fP"
.br
.ti -1c
.RI "class \fBSlowSort\fP"
.br
.ti -1c
.RI "interface \fBSortAlgorithm\fP"
.br
.ti -1c
.RI "class \fBSortUtils\fP"
.br
.ti -1c
.RI "class \fBStoogeSort\fP"
.br
.ti -1c
.RI "class \fBSwapSort\fP"
.br
.ti -1c
.RI "class \fBTask\fP"
.br
.ti -1c
.RI "class \fBTask1\fP"
.br
.ti -1c
.RI "class \fBTask2\fP"
.br
.ti -1c
.RI "class \fBTimSort\fP"
.br
.ti -1c
.RI "class \fBTreeSort\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Author : Siddhant Swarup Mallick Github : https://github.com/siddhant2002 Program description - To sort the LinkList as per sorting technique 
.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
