.TH "com.thealgorithms.datastructures.trees.SegmentTree" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.trees.SegmentTree
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSegmentTree\fP (int n, int arr[])"
.br
.ti -1c
.RI "int \fBconstructTree\fP (int[] arr, int start, int end, int index)"
.br
.ti -1c
.RI "void \fBupdate\fP (int index, int value)"
.br
.ti -1c
.RI "int \fBgetSum\fP (int start, int end)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
