.TH "com.thealgorithms.sorts.SwapSort" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.sorts.SwapSort
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.thealgorithms\&.sorts\&.SortAlgorithm\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The idea of Swap-Sort is to count the number m of smaller values (that are in A) from each element of an array A(1\&.\&.\&.n) and then swap the element with the element in A(m+1)\&. This ensures that the exchanged element is already in the correct, i\&.e\&. final, position\&. The disadvantage of this algorithm is that each element may only occur once, otherwise there is no termination\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
