.TH "com.thealgorithms.conversions.BinaryToOctal" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.conversions.BinaryToOctal
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String args[])"
.br
.ti -1c
.RI "static String \fBconvertBinaryToOctal\fP (int binary)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Converts any Binary number to an Octal Number
.PP
\fBAuthor\fP
.RS 4
Zachary Jones 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static String com\&.thealgorithms\&.conversions\&.BinaryToOctal\&.convertBinaryToOctal (int binary)\fC [static]\fP"
This method converts a binary number to an octal number\&.
.PP
\fBParameters\fP
.RS 4
\fIbinary\fP The binary number 
.RE
.PP
\fBReturns\fP
.RS 4
The octal number 
.RE
.PP

.SS "static void com\&.thealgorithms\&.conversions\&.BinaryToOctal\&.main (String args[])\fC [static]\fP"
Main method
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Command line arguments 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
