.TH "com.thealgorithms.maths.KaprekarNumbers" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.KaprekarNumbers
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static ArrayList< Long > \fBkaprekarNumberInRange\fP (long start, long end)  throws Exception "
.br
.ti -1c
.RI "static boolean \fBisKaprekarNumber\fP (long num)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
