.TH "com.thealgorithms.datastructures.heaps.MinPriorityQueue" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.heaps.MinPriorityQueue
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinsert\fP (int key)"
.br
.ti -1c
.RI "int \fBpeek\fP ()"
.br
.ti -1c
.RI "boolean \fBisEmpty\fP ()"
.br
.ti -1c
.RI "boolean \fBisFull\fP ()"
.br
.ti -1c
.RI "void \fBprint\fP ()"
.br
.ti -1c
.RI "void \fBheapSort\fP ()"
.br
.ti -1c
.RI "int \fBdelete\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Minimum Priority Queue It is a part of heap data structure A heap is a specific tree based data structure in which all the nodes of tree are in a specific order\&. that is the children are arranged in some respect of their parents, can either be greater or less than the parent\&. This makes it a min priority queue or max priority queue\&.
.PP
Functions: insert, delete, peek, isEmpty, print, heapSort, sink 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
