.TH "com.thealgorithms.maths.Armstrong" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.Armstrong
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
An \fBArmstrong\fP number is equal to the sum of the cubes of its digits\&. For example, 370 is an \fBArmstrong\fP number because 3*3*3 + 7*7*7 + 0*0*0 = 370\&. An \fBArmstrong\fP number is often called Narcissistic number\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
