.TH "com.thealgorithms.sorts.OddEvenSort" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.sorts.OddEvenSort
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static void \fBoddEvenSort\fP (int[] arr)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.sorts\&.OddEvenSort\&.oddEvenSort (int[] arr)\fC [static]\fP"
Odd Even Sort algorithms implements
.PP
\fBParameters\fP
.RS 4
\fIarr\fP the array contains elements 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
