.TH "com.thealgorithms.searches.TernarySearch" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.searches.TernarySearch
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.thealgorithms\&.devutils\&.searches\&.SearchAlgorithm\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A ternary search algorithm is a technique in computer science for finding the minimum or maximum of a unimodal function The algorithm determines either that the minimum or maximum cannot be in the first third of the domain or that it cannot be in the last third of the domain, then repeats on the remaining third\&.
.PP
Worst-case performance Θ(log3(N)) Best-case performance O(1) Average performance Θ(log3(N)) Worst-case space complexity O(1)
.PP
\fBAuthor\fP
.RS 4
Podshivalov Nikita (https://github.com/nikitap492) 
.RE
.PP
\fBSee also\fP
.RS 4
SearchAlgorithm 
.PP
\fBIterativeBinarySearch\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
