.TH "com.thealgorithms.others.SkylineProblem" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.others.SkylineProblem
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBuilding\fP"
.br
.ti -1c
.RI "class \fBSkyline\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (int left, int height, int right)"
.br
.ti -1c
.RI "void \fBprint\fP (ArrayList< \fBSkyline\fP > skyline)"
.br
.ti -1c
.RI "ArrayList< \fBSkyline\fP > \fBfindSkyline\fP (int start, int end)"
.br
.ti -1c
.RI "ArrayList< \fBSkyline\fP > \fBmergeSkyline\fP (ArrayList< \fBSkyline\fP > sky1, ArrayList< \fBSkyline\fP > sky2)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
