.TH "com.thealgorithms.misc.matrixTranspose" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.misc.matrixTranspose
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Find the Transpose of Matrix!"
.PP
.PP
Simply take input from the user and print the matrix before the transpose and after the transpose\&.
.PP
\fBNote:\fP Giving proper comments in your program makes it more user friendly and it is assumed as a high quality code\&.
.PP
\fBAuthor\fP
.RS 4
Rajat-Jain29 
.RE
.PP
\fBVersion\fP
.RS 4
11\&.0\&.9 
.RE
.PP
\fBSince\fP
.RS 4
2014-03-31 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
