.TH "com.thealgorithms.datastructures.graphs.DIJSKSTRAS_ALGORITHM" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.datastructures.graphs.DIJSKSTRAS_ALGORITHM \- Clase \fBDIJSKSTRAS_ALGORITHM\fP Esta clase se encarga de realizar el algoritmo de dijkstra dado un grafo\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetK\fP ()"
.br
.RI "Metodo \fBgetK()\fP\&. "
.ti -1c
.RI "int \fBminDist\fP (int dist[], Boolean Set[])"
.br
.RI "Metodo \fBminDist()\fP\&. "
.ti -1c
.RI "String \fBprint\fP (int dist[])"
.br
.RI "Metodo \fBprint()\fP\&. "
.ti -1c
.RI "int \fBaleatorySelectionRCL\fP (int maxTRCL)"
.br
.RI "Metodo aleatorySelectionRCL\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Clase \fBDIJSKSTRAS_ALGORITHM\fP Esta clase se encarga de realizar el algoritmo de dijkstra dado un grafo\&. 
.SH "Member Function Documentation"
.PP 
.SS "int com\&.thealgorithms\&.datastructures\&.graphs\&.DIJSKSTRAS_ALGORITHM\&.aleatorySelectionRCL (int maxTRCL)"

.PP
Metodo aleatorySelectionRCL\&. Se indica un valor maximo y se seleciona una posicion calculada aleatoriamente entre el maximo y 0 
.SS "int com\&.thealgorithms\&.datastructures\&.graphs\&.DIJSKSTRAS_ALGORITHM\&.getK ()"

.PP
Metodo \fBgetK()\fP\&. Retorna el valor de K que esta inicializado a 9 pero esto cambia segun el grafo 
.SS "int com\&.thealgorithms\&.datastructures\&.graphs\&.DIJSKSTRAS_ALGORITHM\&.minDist (int dist[], Boolean Set[])"

.PP
Metodo \fBminDist()\fP\&. A partir de un array de distancias y un conjunto de booleanos asociadas a las posiciones del array devuelve el indice del array con distancia minima 
.SS "String com\&.thealgorithms\&.datastructures\&.graphs\&.DIJSKSTRAS_ALGORITHM\&.print (int dist[])"

.PP
Metodo \fBprint()\fP\&. Recibe un array de distancias y muestra una salida formateada, además retorna en este caso un String con dicha salida 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
