.TH "com.thealgorithms.maths.GCDRecursion" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.maths.GCDRecursion
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static int \fBgcd\fP (int a, int b)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
https://github.com/shellhub/ 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.maths\&.GCDRecursion\&.gcd (int a, int b)\fC [static]\fP"
get greatest common divisor
.PP
\fBParameters\fP
.RS 4
\fIa\fP the first number 
.br
\fIb\fP the second number 
.RE
.PP
\fBReturns\fP
.RS 4
gcd 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
