.TH "com.thealgorithms.others.Dijkstra" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.others.Dijkstra
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void com\&.thealgorithms\&.others\&.Dijkstra\&.main (String[] args)\fC [static]\fP"
main function Will run the code with 'GRAPH' that was defined above\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
