.TH "com.thealgorithms.conversions.HexToOct" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.thealgorithms.conversions.HexToOct
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBhex2decimal\fP (String s)"
.br
.ti -1c
.RI "static int \fBdecimal2octal\fP (int q)"
.br
.ti -1c
.RI "static void \fBmain\fP (String args[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Converts any Hexadecimal Number to Octal
.PP
\fBAuthor\fP
.RS 4
Tanmay Joshi 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static int com\&.thealgorithms\&.conversions\&.HexToOct\&.decimal2octal (int q)\fC [static]\fP"
This method converts a Decimal number to a octal number
.PP
\fBParameters\fP
.RS 4
\fIq\fP The Decimal Number 
.RE
.PP
\fBReturns\fP
.RS 4
The Octal number 
.RE
.PP

.SS "static int com\&.thealgorithms\&.conversions\&.HexToOct\&.hex2decimal (String s)\fC [static]\fP"
This method converts a Hexadecimal number to a decimal number
.PP
\fBParameters\fP
.RS 4
\fIs\fP The Hexadecimal Number 
.RE
.PP
\fBReturns\fP
.RS 4
The Decimal number 
.RE
.PP

.SS "static void com\&.thealgorithms\&.conversions\&.HexToOct\&.main (String args[])\fC [static]\fP"
Main method that gets the hex input from user and converts it into octal\&.
.PP
\fBParameters\fP
.RS 4
\fIargs\fP arguments 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Examen from the source code\&.
