.TH "md_src_main_java_com_thealgorithms_datastructures_queues__r_e_a_d_m_e" 3 "Fri Jan 28 2022" "Examen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_src_main_java_com_thealgorithms_datastructures_queues__r_e_a_d_m_e \- Queue 

.IP "\(bu" 2
The Queue interface is present in the \fCjava\&.util\fP package\&.
.IP "\(bu" 2
It is an ordered list of objects that follows the \fBFIFO\fP (First-In-First-Out) principle\&.
.PP
.SH "Characteristics of a Queue"
.PP
.IP "\(bu" 2
The Queue is used to insert elements at the end of the queue and removes elements from the beginning of the queue\&.
.IP "\(bu" 2
It supports all methods of Collection interface including insertion, deletion etc\&.
.IP "\(bu" 2
LinkedList, ArrayBlockingQueue and PriorityQueue are the most commonly used implementations\&.
.PP
.SH "Declaration"
.PP
\fCQueue<Obj> queue = new PriorityQueue<Obj> ();\fP
.SH "Important operations"
.PP
Operations   Description    Enqueue   Adds an item to the queue    Dequeue   Removes an item from the queue    Front   Gets the front item from the queue    Rear   Gets the last item from the queue   
